"""
train_model.py
===============
Train a Transfer Learning model using MobileNetV2 for 3-class audio classification:
  0: Pest
  1: Beneficial
  2: Noise

Expected preprocessed inputs (generated by preprocess.py):
  data/processed/
    manifest.csv
    spectrograms/Pest/*.npy
    spectrograms/Beneficial/*.npy
    spectrograms/Noise/*.npy

Outputs:
  vibranix_engine.tflite      (Float16-friendly export)
  vibranix_labels.json        (index -> label)
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path
from typing import List, Tuple

import sys
import time

# Ensure HTTPS requests (Keras weight downloads) can validate TLS.
# Some environments need an explicit CA bundle.
try:
    import certifi  # type: ignore

    os.environ.setdefault("SSL_CERT_FILE", certifi.where())
except Exception:
    pass

# #region agent log:env_info
PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOG_PATH = PROJECT_ROOT / ".cursor" / "debug-9f3473.log"

_RUN_ID = "run_import_debug"
_SESSION_ID = "9f3473"

def _agent_log(hypothesis_id: str, location: str, message: str, data: dict) -> None:
    payload = {
        "sessionId": _SESSION_ID,
        "runId": _RUN_ID,
        "hypothesisId": hypothesis_id,
        "location": location,
        "message": message,
        "data": data,
        "timestamp": int(time.time() * 1000),
    }
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")

_agent_log(
    hypothesis_id="H2_wrong_python_env",
    location="scripts/train_model.py:import_start",
    message="Python environment used for imports",
    data={"executable": sys.executable, "version": sys.version},
)
# #endregion

# #region agent log:missing_import
try:
    import numpy as np  # type: ignore
except ModuleNotFoundError as e:
    _agent_log(
        hypothesis_id="H1_deps_missing",
        location="scripts/train_model.py:missing_numpy",
        message="Third-party dependency missing during import",
        data={"missing_module": getattr(e, "name", None)},
    )
    raise

try:
    import tensorflow as tf  # type: ignore
except ModuleNotFoundError as e:
    _agent_log(
        hypothesis_id="H1_deps_missing",
        location="scripts/train_model.py:missing_tensorflow",
        message="Third-party dependency missing during import",
        data={"missing_module": getattr(e, "name", None)},
    )
    raise
# #endregion

from sklearn.model_selection import train_test_split

from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input


DEFAULT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
DEFAULT_TFLITE_PATH = PROJECT_ROOT / "vibranix_engine.tflite"
DEFAULT_LABELS_JSON_PATH = PROJECT_ROOT / "vibranix_labels.json"

CLASS_NAMES = ["Pest", "Beneficial", "Noise"]
NUM_CLASSES = len(CLASS_NAMES)

IMG_HEIGHT = 224
IMG_WIDTH = 224
IMG_CHANNELS = 3


def read_manifest(manifest_path: Path) -> Tuple[List[str], List[int]]:
    paths: List[str] = []
    labels: List[int] = []
    with manifest_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            paths.append(row["path"])
            labels.append(int(row["label_idx"]))
    return paths, labels


def make_tf_dataset(paths: np.ndarray, labels: np.ndarray, batch_size: int, shuffle: bool, seed: int) -> tf.data.Dataset:
    paths = paths.astype("str")
    labels = labels.astype("int32")

    def load_npy(path_bytes: tf.Tensor) -> tf.Tensor:
        # tf.py_function input is sometimes delivered as `bytes` and sometimes as
        # a TensorFlow `EagerTensor` depending on TF/Keras versions.
        def _load(p) -> np.ndarray:
            if isinstance(p, (bytes, bytearray)):
                p_str = p.decode("utf-8")
            else:
                # EagerTensor -> numpy() -> bytes or string.
                p_val = p.numpy() if hasattr(p, "numpy") else p
                if isinstance(p_val, (bytes, bytearray)):
                    p_str = p_val.decode("utf-8")
                else:
                    # numpy scalar / other objects
                    p_str = str(p_val)
            arr = np.load(p_str).astype(np.float32)
            if arr.shape != (IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS):
                raise ValueError(f"Unexpected spectrogram shape: {arr.shape} for {p_str}")
            return arr

        out = tf.py_function(func=_load, inp=[path_bytes], Tout=tf.float32)
        out.set_shape((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
        return out

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if shuffle:
        ds = ds.shuffle(buffer_size=len(paths), seed=seed, reshuffle_each_iteration=True)

    ds = ds.map(lambda p, y: (load_npy(p), y), num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds


def build_model(num_classes: int, base_trainable: bool = False) -> Tuple[tf.keras.Model, tf.keras.Model]:
    raw_inputs = tf.keras.Input(shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), dtype=tf.float32, name="raw_spectrogram")
    x = tf.keras.layers.Lambda(preprocess_input, name="mobilenet_preprocess")(raw_inputs)

    base = MobileNetV2(
        include_top=False,
        weights="imagenet",
        input_tensor=x,
        pooling=None,
    )
    base.trainable = base_trainable

    x = tf.keras.layers.GlobalAveragePooling2D(name="avg_pool")(base.output)
    x = tf.keras.layers.Dropout(0.3, name="dropout")(x)
    outputs = tf.keras.layers.Dense(num_classes, activation="softmax", name="predictions")(x)

    model = tf.keras.Model(inputs=raw_inputs, outputs=outputs, name="vibranix_mobilenetv2")
    return model, base


def compute_class_weights(labels: List[int]) -> dict:
    labels_arr = np.array(labels, dtype=np.int32)
    counts = np.bincount(labels_arr, minlength=NUM_CLASSES)
    total = float(np.sum(counts))
    # Inverse frequency weighting; if a class is absent from `labels`, its weight is 0.
    # (Keras won't use that weight for samples that don't exist, and it avoids huge weights.)
    weights: dict = {}
    for i, c in enumerate(counts):
        if c <= 0:
            weights[i] = 0.0
        else:
            weights[i] = total / (NUM_CLASSES * float(c))
    return weights


def main() -> None:
    parser = argparse.ArgumentParser(description="Train MobileNetV2 on preprocessed Vibranix mel-spectrograms.")
    parser.add_argument("--processed_dir", default=str(DEFAULT_PROCESSED_DIR), help="Path to data/processed/")
    parser.add_argument("--epochs", type=int, default=12)
    parser.add_argument("--fine_tune_epochs", type=int, default=6)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--fine_tune_lr", type=float, default=1e-5)
    parser.add_argument("--unfreeze_last_n_layers", type=int, default=50)
    parser.add_argument("--export_path", default=str(DEFAULT_TFLITE_PATH), help="Output .tflite file")
    parser.add_argument("--labels_json_path", default=str(DEFAULT_LABELS_JSON_PATH), help="Output label mapping json")
    args = parser.parse_args()

    processed_dir = Path(args.processed_dir)
    manifest_path = processed_dir / "manifest.csv"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing manifest: {manifest_path}")

    paths, labels = read_manifest(manifest_path)
    if len(paths) < 3:
        raise RuntimeError("Too few samples. Run preprocess.py first and ensure you have enough data.")

    labels_arr = np.array(labels, dtype=np.int32)
    counts = np.bincount(labels_arr, minlength=NUM_CLASSES)
    present = counts[counts > 0]
    stratify = None
    if len(present) > 1 and int(np.min(present)) >= 2:
        stratify = labels

    X_train_paths, X_val_paths, y_train, y_val = train_test_split(
        paths,
        labels,
        test_size=0.2,
        random_state=args.seed,
        stratify=stratify,
    )

    ds_train = make_tf_dataset(np.array(X_train_paths), np.array(y_train), batch_size=args.batch_size, shuffle=True, seed=args.seed)
    ds_val = make_tf_dataset(np.array(X_val_paths), np.array(y_val), batch_size=args.batch_size, shuffle=False, seed=args.seed)

    class_weights = compute_class_weights(y_train)

    # Phase 1: train top layers
    model, base = build_model(num_classes=NUM_CLASSES, base_trainable=False)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=args.learning_rate),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    callbacks = [
        tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=3, restore_best_weights=True),
        tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", patience=2, factor=0.5, min_lr=1e-7),
    ]

    model.fit(
        ds_train,
        validation_data=ds_val,
        epochs=args.epochs,
        class_weight=class_weights,
        callbacks=callbacks,
        verbose=1,
    )

    # Phase 2: fine-tune the last layers of MobileNetV2.
    # This is usually where transfer learning gives an accuracy boost.
    base.trainable = True
    if args.unfreeze_last_n_layers <= 0:
        print("[train_model] Warning: `--unfreeze_last_n_layers` <= 0; skipping Phase 2 fine-tuning.")
    else:
        for layer in base.layers[:-args.unfreeze_last_n_layers]:
            layer.trainable = False

        model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=args.fine_tune_lr),
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"],
        )
        model.fit(
            ds_train,
            validation_data=ds_val,
            epochs=args.fine_tune_epochs,
            callbacks=callbacks,
            verbose=1,
        )

    # Export to TFLite with float16-friendly conversion.
    export_path = Path(args.export_path)
    export_path.parent.mkdir(parents=True, exist_ok=True)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    tflite_model = converter.convert()
    export_path.write_bytes(tflite_model)

    labels_json_path = Path(args.labels_json_path)
    labels_json_path.write_text(
        json.dumps({str(i): name for i, name in enumerate(CLASS_NAMES)}, indent=2),
        encoding="utf-8",
    )

    print(f"[train_model] Saved: {export_path}")
    print(f"[train_model] Saved: {labels_json_path}")


if __name__ == "__main__":
    main()

